### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ViniciusX22** [ViniciusX22/big-charles#1]
- [ ] **Charles Points**: Sistema de desafios relacionados a mensagens específicas e perguntas de trivia _(possível bot alternativo)_.
- [ ] **Chance de resposta**: Defina a chance de Big Charles responder um pattern reconhecido.
- [ ] **Lista de respostas**: Múltiplas respostas diferentes que serão utilizadas aleatoriamente quando Big Charles reconhecer certo `pattern`.
- [ ] **Interações espontâneas**: Mensagens que Big Charles poderá mandar por conta própria a cada `n` minutos conforme uma chance de `XX%`.
